stages:
  - test

default:
  before_script:
    - pip install tox

python37:
  image: python:3.7
  stage: test
  script:
    - tox -e "py37-{oldest,latest}"

python38:
  image: python:3.8
  stage: test
  script:
    - tox -e "py38-{oldest,latest}"

python39:
  image: python:3.9
  stage: test
  script:
    - tox -e "py39-{oldest,latest}"

python310:
  image: python:3.10
  stage: test
  script:
    - tox -e "py310-{oldest,latest}"

