stages:
  - test
  - release

variables:
  SDIST_FILE: "solrfixtures-${CI_COMMIT_TAG}.tar.gz"
  WHEEL_FILE: "solrfixtures-${CI_COMMIT_TAG}-py3-none-any.whl"
  PYPI_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"

default:
  before_script:
    - pip install tox

python37:
  image: python:3.7
  stage: test
  script:
    - tox -e "py37-{oldest,latest}"

python38:
  image: python:3.8
  stage: test
  script:
    - tox -e "py38-{oldest,latest}"

python39:
  image: python:3.9
  stage: test
  script:
    - tox -e "py39-{oldest,latest}"

python310:
  image: python:3.10
  stage: test
  script:
    - tox -e "py310-{oldest,latest}"

build_and_release:
  image: python:3.10
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - pip install tox
    - pip install twine
  script:
    - tox -e "build_package" -- $CI_COMMIT_TAG
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${PYPI_URL} dist/*

