[tool.poetry]
name = "solrfixtures"
version = "1.0.0"
description = ""
authors = ["Jason Thomale <jason.thomale@unt.edu>"]
packages = [
  { include = "solrfixtures", from = "src"}
]

[tool.poetry.dependencies]
python = "^3.7"
pytz = [
  { version = ">=2020.5", python = "^3.9" },
  { version = ">=2020.4", python = "~3.7 || ~3.8" }
]
ujson = [
  { version = ">=4.2.0", python = "^3.10" },
  { version = ">=4.0.0", python = "~3.9" },
  { version = ">=2.0.0", python = "~3.7 || ~3.8" }
]
[tool.poetry.dev-dependencies]
pytest = [
  { version = "^6.2.5", python = "^3.10" },
  { version = ">=5.4.2", python = "~3.9" },
  { version = ">=5.1.0", python= "~3.7 || ~3.8" }
]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
